### ISSUE TITLE
License.PurchasingCustomerName is misleading

### ISSUE THREAD

**Issue by lilith** [imazen/keyhub#1]
License.PurchasingCustomerName should be nvarchar(1024), and should be called "Owner" or "OwnerName". This is the field which will be locked down after SKU.EditOwnershipDuration expires. We can't prevent Customer fields from being edited, but if this field is locked, it's easy for a human to check for consistency.

Purchasing records will be available in the transaction info as well.

**Comment by stevensomer** [comment]
Agreed. Renamed to OwnerName. 

Added Business rule to WIKI descibing EditOwnershipDuration rule. Perhaps rule needs additional comments. Please review.
