### ISSUE TITLE
CustomerApp.RemoveLicenses must require at least 1 license remain attached. 

### ISSUE THREAD

**Issue by lilith** [imazen/keyhub#2]
As CustomerApps are only connected through their licenses, the server must ensure that they are not disassociated from the last license they contain, to prevent orphaning.

The only way to remove the last license from an application should be by deleting the CustomerApp itself. Obviously, we will need to explain to user they need to add a replacement license before deleting the old one.

**Comment by stevensomer** [comment]
Agreed. This will be one of the business rules verified within the application. Apart from the domainmodel and viewmodel field validation, keyhub will contain a collection of business rule classes, each class implementing one specific rule.

Added page to Wiki as a documentation of business rule.
