### ISSUE TITLE
Exception clicking "edit" on my account page (unpriviledged user)

### ISSUE THREAD

**Issue by lilith** [imazen/keyhub#28]
Error.

An error occurred while processing your request.

CONTROLLERNAME
Account
ACTIONNAME
Edit
MESSAGE
Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'.
MESSAGE
Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'.
INNEREXCEPTION
Object reference not set to an instance of an object.

**Comment by florisrobbemont** [comment]
Fixed
