### ISSUE TITLE
Change all primary keys to GUID

### ISSUE THREAD

**Issue by florisrobbemont** [imazen/keyhub#31]
All primary keys for tables that might be replicated in the future should be of type GUID. It is the only way to ensure consistency across databases.

**Comment by lilith** [comment]
All data types are low-volume, so GUID performance should not even be a consideration. AppIssues is the only table that could, potentially, be high-volume, but it's also something easily changed in the future, as nobody would complain if we dropped all AppIssue rows during an upgrade.

I think it's quite safe to make all primary keys GUIDs, and I don't see any issues with this from a performance standpoint. Are there any implementation hurdles?

**Comment by lilith** [comment]
We should ensure that GUID generation uses newsequentialid, so indexing doesn't suffer. Should be the default.

**Comment by florisrobbemont** [comment]
Done. It uses newid() instead of newsequentualid() as newid is the default for entity framework. It's a bit of a hassle to change this now.

**Comment by lilith** [comment]
Fantastic!
