### ISSUE TITLE
Private key is a password, we need to treat it as such

### ISSUE THREAD

**Issue by lilith** [imazen/keyhub#35]
- Private key can be set, but is never displayed (like a password).
- Public key is always displayed, it is public knowledge
- Private key should be encrypted with a key. Key can be stored in Azure AppSetttings so it's never in code, and is shared across instances. This means that private key discovery will require access to both the database and the environment configuration. 

RSACryptoServiceProvider automatically stores any keys you give it (or it generates) on the filesystem. Use CreateEphemeralKey in CspParameters to avoid.

**Comment by lilith** [comment]
I've fixed the RSACryptoServiceProvider use bugs, but private key encryption hasn't been implement, and the view doesn't display the public key yet.

**Comment by fschwiet** [comment]
Any thoughts on what the name of appsetting should be?  I'm using internalPrivateKey for now.

**Comment by lilith** [comment]
It's not a private key, just a symmetric key -> DatabaseEncryptionKey
