### ISSUE TITLE
Add support for linking multiple OpenID accounts

### ISSUE THREAD

**Issue by lilith** [imazen/keyhub#40]
If a user logs in with OpenId, and there is an existing user with the same e-mail address, but a different OpenID system, we should prompt the user to link both accounts, by having them log in with the original OpenId system. After that point, both OpenID logins will access the same account.

**Comment by lilith** [comment]
What is the status on this? Can we close this issue?

**Comment by fschwiet** [comment]
Linking OpenID providers was completed awhile ago.  Just today I updated /Account/LinkAccount page to also show what OpenID providers are linked, and allow for them to be unlinked.  The user is only allowed to unlink a login if they have other ways to login.
