### ISSUE TITLE
Switch to ASP.NET Identity 2.0

### ISSUE THREAD

**Issue by lilith** [imazen/keyhub#62]
Switch KeyHub to ASP.NET Identity 2.0. Make all unit and integration tests pass.

http://blogs.msdn.com/b/webdev/archive/2014/03/20/test-announcing-rtm-of-asp-net-identity-2-0-0.aspx

**Comment by spacedsweden** [comment]
Is this done?

**Comment by lilith** [comment]
Nope. Are you interested in using the project?

**Comment by matsprea** [comment]
Asp.Net Identity 2.0 requires EntityFramework (≥ 6.1.0)
https://www.nuget.org/packages/Microsoft.AspNet.Identity.EntityFramework/2.0.0

This project uses EntityFramework 5

This is a guide to migrate from Sql Membership to AspNet Identity http://www.asp.net/identity/overview/migrations/migrating-an-existing-website-from-sql-membership-to-aspnet-identity

**Comment by coder11** [comment]
Is the bounty still applicable?
https://www.bountysource.com/issues/2012813-switch-to-asp-net-identity-2-0

**Comment by Cussa** [comment]
Is the bounty still available?
https://www.bountysource.com/issues/2012813-switch-to-asp-net-identity-2-0

**Comment by lilith** [comment]
Yes, the bounty is available - funds reserved - but this project is dead. If you'd like I could issue payment *through* that bounty for other work - work that might actually be worthwhile. 
The .NET projects that are currently important to me are
https://github.com/imazen/imageflow-dotnet
https://github.com/imazen/resizer

**Comment by Cussa** [comment]
I see no problems on that. Please, how can we talk to see which one could be the chosen task?

**Comment by ghost** [comment]
@lilith Is your offer still open?

**Comment by lilith** [comment]
Hey @Cussa and @braewoods, sorry for the late reply, I guess I don't have notifications on for this thread or it got lost. Email lilith@imazen.io for further conversation :)
